### ISSUE TITLE
quickstart demo

### ISSUE THREAD

**Issue by Izopi4a** [Codeception/phalcon-demo#5]
@sergeyklay can you make phalcon quick starter here http://codeception.com/quickstart please.

I haven't used codeception, i am just starting to know it, otherwise i would help

**Comment by sergeyklay** [comment]
@Izopi4a Could you please explain a bit more?

**Comment by Izopi4a** [comment]
there are buttons ( frameworks ) on the right side and phalcon is missing

**Comment by sergeyklay** [comment]
I'll try to sort out ASAP

**Comment by ruudboon** [comment]
Closing this in favour of https://github.com/Codeception/codeception.github.com/pull/204
